### ISSUE TITLE
Word Vectors

### ISSUE THREAD

**Issue by pjdrm** [alexalemi/segmentation#1]
Hi,

I would like to use the segmentation algorithm but the word vectors are missing ("/home/aaa244/storage/arxiv_glove/bigrun/data/mats/vecs.npy"). Is it possible to make them available?

Thank you,
Pedro Mota

**Comment by alexalemi** [comment]
You can download pretrained word vectors from other sources, including the word2vec project page: https://code.google.com/archive/p/word2vec/
Or the GloVe project page: http://nlp.stanford.edu/projects/glove/

**Comment by pjdrm** [comment]
Hi Alex,

thank you for the fast answer.

Best,
Pedro
